name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - frontend
      - backend
      - database

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    concurrency: 
      group: ci-client-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Packages
        run: pnpm install
        working-directory: ./frontend

      - name: Lint Client
        run: pnpm lint:ci
        working-directory: ./frontend

      - name: Build Client
        run: pnpm build
        working-directory: ./frontend
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

  supabase:
    name: Supabase
    runs-on: ubuntu-latest
    concurrency: 
      group: ci-supabase-${{ github.ref }}
      cancel-in-progress: true
    if: github.event_name == 'pull_request'

    steps:
      - name: Start Supabase Stack
        run: supabase db start --workdir ./database

      - name: Lint Migrations
        run: supabase db lint --workdir ./database
      
      - name: Test Migrations
        run: supabase db test --workdir ./database
